version: '3.8'

services:
  openqa:
    build: .
    image: openqa_dev
    ports:
      - 9526:9526
    privileged: true
    volumes:
      - ./share:/share
    healthcheck:
      test: ["CMD", "[", "-f", "/home/openqa/healthcheck.lock", "]"]
      interval: 20s
      timeout: 2s
      retries: 10
      start_period: 20s
